#import = ["/home/linuxin/dotfiles/alacritty/color.toml"]

import = ["~/.config/alacritty/themes/themes/gruvbox_material.toml"]

live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

#[colors]
#draw_bold_text_with_bright_colors = false

#[[colors.indexed_colors]]
#color = "0xf4a261"
#index = 16

#[[colors.indexed_colors]]
#color = "0xd67ad2"
#index = 17

[env]
TERM="xterm-256color"

[font]
size = 11.0

[font.normal]
family = "RobotoMono Nerd Font"
style = "Regular"

[font.bold]
family = "RobotoMono Nerd Font"
style = "Bold"

[font.italic]
family = "RobotoMono Nerd Font"
style = "Italic"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 15000
multiplier = 3

[selection]
save_to_clipboard = false
